### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by lmuller18** [ShafSpecs/remix-pwa#12]
## Issue
Ran following:
`yarn add esbuild`
`yarn add remix-pwa`

(also tried `npm` for both after running into this issue. Same issues`

Output:
```
error app/node_modules/remix-pwa: Command failed.
Exit code: 1
Command: npm run start
Arguments: 
Directory: app/node_modules/remix-pwa
Output:
> remix-pwa@0.3.4 start
> node --loader ts-node/esm .\cli.ts

(node:7497) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
app/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:383
    throw new ERR_MODULE_NOT_FOUND(
          ^
CustomError: Cannot find module 'app/node_modules/remix-pwa/.cli.ts' imported from app/node_modules/remix-pwa/
    at finalizeResolution (app/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:383:11)
    at moduleResolve (app/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:818:10)
    at Object.defaultResolve (app/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:929:11)
    at resolve (app/node_modules/ts-node/src/esm.ts:163:38)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ESMLoader.import (node:internal/modules/esm/loader:332:22)
    at node:internal/modules/run_main:54:28
    at loadESM (node:internal/process/esm_loader:88:11)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by ShafSpecs** [comment]
This is very weird, it was an issue in v0.3.3 but was patched in v0.3.4. Could you please try again and report what happens?

**Comment by ShafSpecs** [comment]
Give me a few moments to review the code and get back to you.

**Comment by ShafSpecs** [comment]
I have reviewed possible flaws and have bumped it v0.3.5, could you try again?

The funny thing here is I can't reproduce it since it works for me but try running it again 😄

**Comment by ShafSpecs** [comment]
Ok. Could you display the error beneath it though? The last errors? Thanks

**Comment by lmuller18** [comment]
I see the same / similar issue with NPM as well. This is NPM output: 

```
> npm i remix-pwa
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm ERR! code 130
npm ERR! path /app/node_modules/remix-pwa
npm ERR! command failed
npm ERR! command sh -c npm i -D @types/fs-extra @types/inquirer @types/prettier && npm run start
npm ERR! added 1280 packages, and audited 1281 packages in 19s
npm ERR! 
npm ERR! 205 packages are looking for funding
npm ERR!   run `npm fund` for details
npm ERR! 
npm ERR! found 0 vulnerabilities
npm ERR! 
npm ERR! > remix-pwa@0.3.6 start
npm ERR! > node --loader ts-node/esm cli.ts
npm ERR! 
npm ERR! 
npm ERR! Welcome to Remix PWA!
npm ERR! 
npm ERR! ? Is this a TypeScript or JavaScript project? Pick the opposite for chaos! (Use 
npm ERR! arrow keys)
npm ERR! ❯ TypeScript 
npm ERR!   JavaScript 
npm ERR! npm WARN idealTree Removing dependencies.@types/fs-extra in favor of devDependencies.@types/fs-extra
npm ERR! npm WARN idealTree Removing dependencies.@types/inquirer in favor of devDependencies.@types/inquirer
npm ERR! npm WARN idealTree Removing dependencies.@types/prettier in favor of devDependencies.@types/prettier
npm ERR! npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm ERR! npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm ERR! (node:17853) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
npm ERR! (Use `node --trace-warnings ...` to show where the warning was created)

npm ERR! A complete log of this run can be found in:
npm ERR!     /user/.npm/_logs/2022-02-19T02_53_07_210Z-debug-0.log
```

**Comment by ShafSpecs** [comment]
Could you please run `npm i remix-pwa@0.3.4`? Looking at your logs, the command `npm i -D @types/fs-extra @types/inquirer @types/prettier && npm run start` it is running isn't the lastest version

**Comment by lmuller18** [comment]
```
> npm i remix-pwa@latest
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm ERR! path /app/node_modules/remix-pwa
npm ERR! command failed
npm ERR! signal SIGINT
npm ERR! command sh -c npm run start
npm ERR! > remix-pwa@0.3.7 start
npm ERR! > node --loader ts-node/esm cli.ts
npm ERR! 
npm ERR! 
npm ERR! Welcome to Remix PWA!
npm ERR! 
npm ERR! ? Is this a TypeScript or JavaScript project? Pick the opposite for chaos! (Use 
npm ERR! arrow keys)
npm ERR! ❯ TypeScript 
npm ERR!   JavaScript 
npm ERR! (node:18113) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
npm ERR! (Use `node --trace-warnings ...` to show where the warning was created)

npm ERR! A complete log of this run can be found in:
npm ERR!     /user/.npm/_logs/2022-02-19T03_06_11_974Z-debug-0.log
```

**Comment by ShafSpecs** [comment]
The fact that everything outputs `npm ERR!` is baffling to me. I just re-installed it and it worked, I would debug the issue now. Could you try installing another package with npm and see if it works?

**Comment by ShafSpecs** [comment]
I would give `remix-pwa` a full rundown with yarn and npm to spare these errors. Might take a few hours

**Comment by ShafSpecs** [comment]
@lmuller18 Could you possibly attempt the install again, please? Just want confirmation it's good to go

**Comment by ShafSpecs** [comment]
Have you encountered any success? I made some changes, notably v0.4.8, v0.4.10 & `@latest`.

**Comment by ShafSpecs** [comment]
> *Closing this issue due to inactivity, feel free to re-open the issue if the issue still persists.*

**Comment by roydigerhund** [comment]
I have the same problem, neither `yarn add -D remix-pwa@0.4.10` nor `npm i -D remix-pwa@0.4.10` works.

<img width="722" alt="image" src="https://user-images.githubusercontent.com/10884413/155405404-afc89f3f-1abc-418a-ab03-5a78d1763249.png">

**Comment by ShafSpecs** [comment]
I would also suggest not using v0.4 anymore, v0.6.0 is just around the corner and it does include some precautions (I hope) for some of these issues

**Comment by roydigerhund** [comment]
@ShafSpecs thanks for your reply. The problem does not seem to be connected to yarn. As stated in my comment, I tried with yarn and npm and both failed with a SIGINT. Both tries can be seen in the screenshot. I also tried with the versions  `@0.5.0` and `@latest` without success.

But good news, I just tried again with `@0.6.1` and it worked. Seems like without the prompt about JS/TS it works just fine.

**Comment by ShafSpecs** [comment]
> @ShafSpecs thanks for your reply. The problem does not seem to be connected to yarn. As stated in my comment, I tried with yarn and npm and both failed with a SIGINT. Both tries can be seen in the screenshot. I also tried with the versions `@0.5.0` and `@latest` without success.
> 
> But good news, I just tried again with `@0.6.1` and it worked. Seems like without the prompt about JS/TS it works just fine.

Yep. I just released v0.6.1 patch due to SIGINT. The question should still be asked though, I would release a v0.6.2 patch to address that soon. 
I went through docs and I think I have managed to pinpoint the cause. I won't say the cause yet till I am sure and `v0.6.2` works for everyone

**Comment by roydigerhund** [comment]
Which version is now installed if the prompt didn't show up. Typescript or Javascript?

**Comment by ShafSpecs** [comment]
I have released the patch. Pls let me know if the bug persists, I have tested it and it works again with the questions

**Comment by roydigerhund** [comment]
Version `@0.6.2` fails again for me, both in yarn and npm.

**Comment by ShafSpecs** [comment]
> Version `@0.6.2` fails again for me, both in yarn and npm.

Ok, thanks. I have gotten the problem (most likely) 👍.

I am literally confused as to why it fails for some and works for some

**Comment by roydigerhund** [comment]
By the way, I'm using:

- node v16.13.1
- yarn 1.22.17
- macOS 12.2.1

**Comment by ShafSpecs** [comment]
> By the way, I'm using:
> 
> * node v16.13.1
> * yarn 1.22.17
> * macOS 12.2.1

I would recommend downgrading to node v14.16.* and trying again. That's the LTS version and the most stable. I would still release patches here

**Comment by roydigerhund** [comment]
Would it be a workaround to select the language via a variable? Like this:
`yarn add -D remix-pwa@latest --typescript`

**Comment by roydigerhund** [comment]
is there a way to know if everything got installed correctly? I got a SyntaxError message during the installation and I think not all files got installed. For example, there is no `pwa-utils.server`.

Do you have a complete list of changes which should have been made?

**Comment by ShafSpecs** [comment]
> 

Yes. If you head to the `templates/{your-lang}` folder in the repo, that's where all changes are. 

The reason you don't have the files is that the installation exited before it was able to inject the files. I have released `v0.6.4` that changes the question package completely. I hope that fixes it

**Comment by ShafSpecs** [comment]
Well, that's a massive step forward. So, it was the question that caused the issue. About client.entry, I can quickly make a few changes now and release it. With regards to the root, I would try to reduce syntax errors, it should be an easy fix. Thx 👍

**Comment by roydigerhund** [comment]
>  With regards to the root, I would try to reduce syntax errors, it should be an easy fix.

That's the strange thing, in the original `root.tsx` there is no syntax error. And also with the applied changes (let location ...) as seen in the screenshot, this still shouldn't be a syntax error. But I can easily fix this for me by removing the line temporarely.

**Comment by roydigerhund** [comment]
Hmm, `entry.client.tsx` still won't get updated. 

Another thing I saw is that the imports are missing. In `root.tsx` for example `useLocation` and `useMatches` are not imported. Does it maybe make more sense to create all those changes manually?

**Comment by ShafSpecs** [comment]
> Hmm, `entry.client.tsx` still won't get updated.

**Update:**
Now fixed
https://github.com/ShafSpecs/remix-pwa/issues/15

**Comment by ShafSpecs** [comment]
> *This issue is closed and locked due to inactivity and the issue being solved. To continue, please open another issue.*
