### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/app/entry.client.tsx'

### ISSUE THREAD

**Issue by garth** [ShafSpecs/remix-pwa#24]
```
pnpx remix-pwa
Welcome to Remix PWA!

✔ Is this a TypeScript or JavaScript project? Pick the opposite for chaos! · TypeScript
✔ Do you want to immediately run "npm install"? (Y/n) · false
Error: ENOENT: no such file or directory, open '/app/entry.client.tsx'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at /node_modules/.pnpm/remix-pwa@0.8.1_@babel+core@7.18.2/node_modules/remix-pwa/dist/cli.js:72:39
    at step (/node_modules/.pnpm/remix-pwa@0.8.1_@babel+core@7.18.2/node_modules/remix-pwa/dist/cli.js:34:23)
    at Object.next (/node_modules/.pnpm/remix-pwa@0.8.1_@babel+core@7.18.2/node_modules/remix-pwa/dist/cli.js:15:53)
    at /node_modules/.pnpm/remix-pwa@0.8.1_@babel+core@7.18.2/node_modules/remix-pwa/dist/cli.js:9:71
    at new Promise (<anonymous>)
    at __awaiter (/node_modules/.pnpm/remix-pwa@0.8.1_@babel+core@7.18.2/node_modules/remix-pwa/dist/cli.js:5:12)
    at Run (/node_modules/.pnpm/remix-pwa@0.8.1_@babel+core@7.18.2/node_modules/remix-pwa/dist/cli.js:47:12)
    at /node_modules/.pnpm/remix-pwa@0.8.1_@babel+core@7.18.2/node_modules/remix-pwa/dist/cli.js:125:63 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/app/entry.client.tsx'
```

**Comment by ShafSpecs** [comment]
It means you don't have a client file. Because `remix-pwa` requires the entry client file to work

**Comment by garth** [comment]
In my case it's in src/app. Maybe the cli should ask?

**Comment by ShafSpecs** [comment]
> In my case it's in src/app. 

Oh yeaaa..... that's why. 

> Maybe the cli should ask?

Good idea, do you have any recommendations or features you would like to see asides from that?

**Comment by ShafSpecs** [comment]
https://github.com/ShafSpecs/remix-pwa/commit/889f3ae638f652062d96475b98c13902d3591a74
Issue fixed and resolved.
