### ISSUE TITLE
Error: [node-persist][readFile] ... does not look like a valid storage file!

### ISSUE THREAD

**Issue by JellyBrick** [ShafSpecs/remix-pwa#25]
```javascript
POST /resources/subscribe 200 - - 3.177 ms
Error: [node-persist][readFile] .node-persist/storage/b48b13e73a6ac2a86dc54425dd24d9ff does not look like a valid storage file!
    at ./libre-billboardoo-frontend/node_modules/node-persist/src/local-storage.js:314:89
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

**Comment by ShafSpecs** [comment]
Could you please elaborate on the issue? When does this error occur? While using the Push API? At random intervals?
Please provide more information

**Comment by JellyBrick** [comment]
At random intervals.

**Comment by JellyBrick** [comment]
```javascript
GET / 200 - - 35.708 ms
POST /resources/subscribe 200 - - 3.725 ms
GET /resources/manifest.json 200 - - 1.426 ms
GET /rank/hourly?_data=routes%2Frank%2Fhourly 200 - - 26.390 ms
GET / 200 - - 37.130 ms
GET /rank/hourly 200 - - 106.870 ms
GET /?_data=routes%2Findex 200 - - 7.490 ms
GET / 200 - - 35.648 ms
POST /resources/subscribe 200 - - 2.841 ms
Error: [node-persist][readFile] .node-persist/storage/b48b13e73a6ac2a86dc54425dd24d9ff does not look like a valid storage file!
    at ./libre-billboardoo-frontend/node_modules/node-persist/src/local-storage.js:314:89
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

**Comment by ShafSpecs** [comment]
> At random intervals.

That's weird. Are you using the Push API in the project?

**Comment by JellyBrick** [comment]
> > At random intervals.
> 
> That's weird. Are you using the Push API in the project?

No, I just used `npx remix-pwa@latest`

Maybe this is a problem?
https://github.com/wakboardoo/libre-billboardoo-frontend/blob/19aa2a99e7efb9cde187e64b087d67730f3e6612/app/entry.client.tsx#L46-L73

**Comment by ShafSpecs** [comment]
Yes. You can disable it, that part is for Push API. Remove that section, restart the app. 
*You might want to delete caches and unregister the SW then re-register it.*

**Comment by ShafSpecs** [comment]
*Closing issue as resolved*
