### ISSUE TITLE
node-persist error makes the application to crash

### ISSUE THREAD

**Issue by NdozHH** [ShafSpecs/remix-pwa#35]
Hello, any idea what is the cause of this error?
I have the latest version of remix-pwa and the application is deployed in Vercel, and sometimes it crashes and generates this error.

```bash
2022-07-19T04:35:38.321Z	c2e38db0-e42e-4b5c-ac95-f50ec717eb7e	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: ENOENT: no such file or directory, mkdir '/var/task/.node-persist'","reason":{"errorType":"Error","errorMessage":"ENOENT: no such file or directory, mkdir '/var/task/.node-persist'","code":"ENOENT","errno":-2,"syscall":"mkdir","path":"/var/task/.node-persist","stack":["Error: ENOENT: no such file or directory, mkdir '/var/task/.node-persist'"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: ENOENT: no such file or directory, mkdir '/var/task/.node-persist'","    at process.<anonymous> (file:///var/runtime/index.mjs:775:15)","    at process.emit (node:events:539:35)","    at process.emit (/var/task/node_modules/source-map-support/source-map-support.js:516:21)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
[ERROR] [1658205338322] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 400.
RequestId: 4ba770e1-f539-4c3c-b041-3fb60360f0ac Error: Runtime exited with error: exit status 128
Runtime.ExitError
```

Thank you!

**Comment by ShafSpecs** [comment]
Are you using Push API? If not, I would recommend removing `remix-pwa` and re-doing a fresh reinstall

**Comment by ShafSpecs** [comment]
**The newest release of `remix-pwa` addresses this**

*This issue was closed due to inactivity*

**Comment by ShafSpecs** [comment]
**The newest release of `remix-pwa` addresses this**

*This issue was closed due to inactivity*

**Comment by ShafSpecs** [comment]
**The newest release of `remix-pwa` addresses this**

*This issue was closed due to inactivity*
