### ISSUE TITLE
MacOs instalation failure

### ISSUE THREAD

**Issue by conmute** [ShafSpecs/remix-pwa#37]
**Whats happening?**

On instalation steps:

```sh
➜  main npx remix-pwa@latest
Welcome to Remix PWA!

✔ Is this a TypeScript or JavaScript project? Pick the opposite for chaos! · TypeScript
✔ What caching strategy do you want to use? Check out the docs for more info. · Just-In-Time Caching
✔ What features of remix-pwa do you need? Don't be afraid to pick all! · Service Workers, Web Manifest, Push Notifications, PWA Client Utilities, Development Icons
✔ What is the location of your Remix app? · src/app
✔ Do you want to immediately run "npm install"? (Y/n) · false
Error: ENOENT: no such file or directory, open '/Users/ross/Documents/target/Conmution/ukraine-stands/main/src/app/entry.client.tsx'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at /Users/ross/.npm/_npx/40109/lib/node_modules/remix-pwa/dist/cli.js:79:39
    at step (/Users/ross/.npm/_npx/40109/lib/node_modules/remix-pwa/dist/cli.js:34:23)
    at Object.next (/Users/ross/.npm/_npx/40109/lib/node_modules/remix-pwa/dist/cli.js:15:53)
    at /Users/ross/.npm/_npx/40109/lib/node_modules/remix-pwa/dist/cli.js:9:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/ross/.npm/_npx/40109/lib/node_modules/remix-pwa/dist/cli.js:5:12)
    at Run (/Users/ross/.npm/_npx/40109/lib/node_modules/remix-pwa/dist/cli.js:48:12)
    at /Users/ross/.npm/_npx/40109/lib/node_modules/remix-pwa/dist/cli.js:182:42 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/ross/Documents/target/Conmution/ukraine-stands/main/src/app/entry.client.tsx'
}
```

Expected to have success of cli run, not a failure…

System:

<img width="627" alt="Screenshot 2022-07-29 at 22 24 04" src="https://user-images.githubusercontent.com/938118/181830201-6f1269c5-1346-407e-800f-d58b80797ff8.png">

**Comment by ShafSpecs** [comment]
Do you have your `entry.client` file in your `src/app `dir?

**Comment by ShafSpecs** [comment]
This issue is caused by an absence of `entry.client.tsx` in the `app/` dir.

**Comment by ShafSpecs** [comment]
*This issue is stale and inactive. If you have any further questions, please open a new issue :+1:*
