### ISSUE TITLE
SyntaxError: Unexpected token - Installation fails

### ISSUE THREAD

**Issue by moishinetzer** [ShafSpecs/remix-pwa#38]
```sh
$ npx remix-pwa@latest
Welcome to Remix PWA!

√ Is this a TypeScript or JavaScript project? Pick the opposite for chaos! · TypeScript

√ What caching strategy do you want to use? Check out the docs 
for more info. · Precaching

√ What features of remix-pwa do you need? Don't be afraid to pick all! · No items were selected

√ What is the location of your Remix app? · app
√ Do you want to immediately run "npm install"? (Y/n) · true
SyntaxError: Unexpected token (36:275)
  34 | }, [location]);
  35 |
> 36 | return ( <html lang="en" className={` flex min-h-screen 
flex-col bg-slate-100 font-montserrat scrollbar ${SCROLL_BAR_STYLE}`} > <head> <Meta /> <Links /> </head> <body className="flex min-h-screen flex-col text-2xl"> <Outlet /> <Scripts /> <LiveReload /> </body> </html> ); } 
     |



                             ^
    at p (C:\Users\Moish\Documents\Repos\instabis\node_modules\prettier\parser-babel.js:22:1038)
    at d (C:\Users\Moish\Documents\Repos\instabis\node_modules\prettier\parser-babel.js:22:1271)
    at Object.parse (C:\Users\Moish\Documents\Repos\instabis\node_modules\prettier\parser-babel.js:27:50424)
    at Object.parse (C:\Users\Moish\Documents\Repos\instabis\node_modules\prettier-plugin-tailwindcss\dist\index.js:146:3860) 
    at Object.parse (C:\Users\Moish\Documents\Repos\instabis\node_modules\prettier\index.js:7334:23)
    at coreFormat (C:\Users\Moish\Documents\Repos\instabis\node_modules\prettier\index.js:8645:18)
    at formatWithCursor2 (C:\Users\Moish\Documents\Repos\instabis\node_modules\prettier\index.js:8837:18)
    at C:\Users\Moish\Documents\Repos\instabis\node_modules\prettier\index.js:37229:12
    at Object.format (C:\Users\Moish\Documents\Repos\instabis\node_modules\prettier\index.js:37243:12)
    at C:\Users\Moish\Documents\Repos\instabis\node_modules\remix-pwa\dist\cli.js:106:34 {
  loc: { start: { line: 36, column: 275 } },
  codeFrame: '\x1B[0m \x1B[90m 34 |\x1B[39m }\x1B[33m,\x1B[39m 
[location])\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 35 |\x1B[39m\x1B[0m\n' +
    '\x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 36 |\x1B[39m \x1B[36mreturn\x1B[39m ( \x1B[33m<\x1B[39m\x1B[33mhtml\x1B[39m lang\x1B[33m=\x1B[39m\x1B[32m"en"\x1B[39m className\x1B[33m=\x1B[39m{\x1B[32m` flex min-h-screen flex-col bg-slate-100 font-montserrat scrollbar ${SCROLL_BAR_STYLE}`\x1B[39m} \x1B[33m>\x1B[39m \x1B[33m<\x1B[39m\x1B[33mhead\x1B[39m\x1B[33m>\x1B[39m \x1B[33m<\x1B[39m\x1B[33mMeta\x1B[39m \x1B[35m/> <Links /\x1B[39m\x1B[33m>\x1B[39m \x1B[33m<\x1B[39m\x1B[35m/head> <body className="flex min-h-screen flex-col text-2xl"> <Outlet /\x1B[39m\x1B[33m>\x1B[39m \x1B[33m<\x1B[39m\x1B[33mScripts\x1B[39m \x1B[35m/> <LiveReload /\x1B[39m\x1B[33m>\x1B[39m \x1B[33m<\x1B[39m\x1B[33m/\x1B[39m\x1B[33mbody\x1B[39m\x1B[33m>\x1B[39m \x1B[33m<\x1B[39m\x1B[33m/\x1B[39m\x1B[33mhtml\x1B[39m\x1B[33m>\x1B[39m )\x1B[33m;\x1B[39m } \x1B[0m\n' +
    '\x1B[0m \x1B[90m    |\x1B[39m



                                                         \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m'
}
```

OS: Windows
Node: Latest

**Comment by ShafSpecs** [comment]
You selected none of remix-pwa options which is weird (considering you picked `Precaching` above and didn't select Service Worker later on.)

**Comment by moishinetzer** [comment]
I did it to showcase the error, unfortunately this error occurs no matter which combination of options I use...

**Comment by sachinkaria** [comment]
I am also experiencing this issue with all combinations

**Comment by ShafSpecs** [comment]
Weird but interesting. I would look at it and roll out a fix

**Comment by ShafSpecs** [comment]
@moishinetzer Still bugs me, is this issue just for this project or all your projects?

**Comment by moishinetzer** [comment]
I haven't tried on a base project. This was done on a specific private project of mine. 

I have sent you an invite so you can test it if you would like.

**Comment by moishinetzer** [comment]
Any updates?

**Comment by ShafSpecs** [comment]
> I haven't tried on a base project. This was done on a specific private project of mine. 
> 
> I have sent you an invite so you can test it if you would like. 

Alright. This is a weir  issue

**Comment by Sven-Quantix** [comment]
Any updates? Issue still persists.

**Comment by X3rom-S** [comment]
This is strange.. but you can try this method, maybe it will be solved for you too
**Delete all the comments in the root.jsx file**
then run npx remix-pwa@latest

**Comment by ShafSpecs** [comment]
*This issue is presumably solved.* 
https://github.com/ShafSpecs/remix-pwa/issues/38#issuecomment-1253270930 works. Weird that comments interfere with the code generation though, would look at it.

**If anyone has any further questions, please open a new issue*
