### ISSUE TITLE
Installation not Working

### ISSUE THREAD

**Issue by chuckstock** [ShafSpecs/remix-pwa#50]
Running a fresh installation with these options: 
```
✔ Is this a TypeScript or JavaScript project? Pick the opposite for chaos! · TypeScript
✔ What caching strategy do you want to use? Check out the docs for more info. · Just-In-Time Caching
✔ What features of remix-pwa do you need? Don't be afraid to pick all! · Service Workers, Web Manifest, Push Notifications, PWA Client Utilities, Development Icons
✔ What is the location of your Remix app? · arena-pwa
✔ Do you want to immediately run "npm install"? (Y/n) · false
```

Ends up throwing this error:
```
Error: ENOENT: no such file or directory, open '/Users/charlieblackstock/repos/arena-pwa/entry.client.tsx'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at /Users/charlieblackstock/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:79:39
    at step (/Users/charlieblackstock/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:34:23)
    at Object.next (/Users/charlieblackstock/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:15:53)
    at /Users/charlieblackstock/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:9:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/charlieblackstock/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:5:12)
    at Run (/Users/charlieblackstock/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:48:12)
    at /Users/charlieblackstock/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:182:42 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/charlieblackstock/repos/arena-pwa/entry.client.tsx'
}
```

**Comment by ShafSpecs** [comment]
The issue is due to the second to the last prompt:
```
✔ What is the location of your Remix app? · arena-pwa
```

This prompt refers to the location of the `app` folder in your remix directory. Normally it is: `arena-pwa/app`, except you changed it manually like `arena-pwa/src`, you can just move on without changing anything. Because the `app` location has been selected already. Take a look at [this link](https://github.com/ShafSpecs/remix-pwa#app-location)

**Comment by chuckstock** [comment]
If i run with just default setup I still get the error:
```
Welcome to Remix PWA!

✔ Is this a TypeScript or JavaScript project? Pick the opposite for chaos! · TypeScript
✔ What caching strategy do you want to use? Check out the docs for more info. · Precaching
✔ What features of remix-pwa do you need? Don't be afraid to pick all! · Service Workers, Web Manifest, Push Notifications, PWA Client Utilities, Development Icons
✔ What is the location of your Remix app? · app
✔ Do you want to immediately run "npm install"? (Y/n) · false
Error: ENOENT: no such file or directory, open '/Users/charlieblackstock/repos/arena-next/apps/pwa/app/entry.client.tsx'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at /Users/charlieblackstock/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:79:39
    at step (/Users/charlieblackstock/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:34:23)
    at Object.next (/Users/charlieblackstock/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:15:53)
    at /Users/charlieblackstock/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:9:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/charlieblackstock/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:5:12)
    at Run (/Users/charlieblackstock/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:48:12)
    at /Users/charlieblackstock/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:182:42 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/charlieblackstock/repos/arena-next/apps/pwa/app/entry.client.tsx'
}
```

**Comment by ShafSpecs** [comment]
Weird. Which folder are you running `remix-pwa` in?

**Comment by chuckstock** [comment]
Yeah it's a monorepo. It looks like there are a few errors in the `cli.ts`. I was going submit a PR, but I keep running into more bugs. First is `readFileSync` throws an error if the file doesn't exist, so some places it needs to be changed to `existsSync`. Secondly, they are searching for `.tsx` or `.jsx` files from the templates but those files are either `.ts` or `.js`. I was fixing those and ran into more errors so I figured I'd just let you know since you might have some more domain knowledge on what is happening.

**Comment by ShafSpecs** [comment]
Interesting. Are you running the `npx remix-pwa` command in `arena-next` or `arena-next/apps/pwa`? I have some made some changes but haven't found time to document them properly and ship a new release

> First is `readFileSync` throws an error if the file doesn't exist, so some places it needs to be changed to `existsSync`

I am planning to update the cli later this year to make it more autonated and also to handle errors better.

**Comment by ShafSpecs** [comment]
*Due to inactivity, this isssue would be locked. Please open a new issue to address new problems*
